org.gradle.jvmargs=-Xmx4G
loom.platform=neoforge

archives_base_name=cobblemon-pc-on-a-stick
mod_id=pc_on_a_stick
mod_version=1.x-DEV-SNAPSHOT
maven_group=dev.matthiesen
mod_name=Cobblemon PC on a Stick
mod_description=Ever heard of the Crafting Table on a Stick? Well, now there is a PC on a Stick too!
mod_license=MIT License
mod_license_url=https://github.com/Matthiesen-dev/pc-on-a-stick/blob/main/LICENSE
mod_author=Adam Matthiesen
mod_author_id=adammatthiesen
mod_author_url=https://github.com/Adammatthiesen
github_url=https://github.com/Matthiesen-dev/pc-on-a-stick
git_url=github.com/Matthiesen-dev/pc-on-a-stick
modrinth_url=https://modrinth.com/mod/cobblemon-pc-on-a-stick

minecraft_version=1.21.1

crafting_stick_version=1.21.0.4
curios_version=9.5.1+1.21.1